name: yc_flutter_plugin
description: A new Flutter plugin.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^2.1.16
  cached_network_image: ^1.1.1
  pull_to_refresh: ^1.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.yihce.yc_flutter_plugin
    pluginClass: YcFlutterPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - images/bpbase_default_holder_dark_normal.png
    - images/bpbase_default_holder_dark_small.png
    - images/bpbase_default_holder_light_big.png
    - images/bpbase_default_holder_light_normal.png
    - images/bpbase_default_holder_light_small.png
    - images/ic_loading_0.png
    - images/ic_loading_1.png
    - images/ic_loading_2.png
    - images/ic_loading_3.png
    - images/ic_loading_4.png
    - images/ic_loading_5.png
    - images/ic_loading_6.png
    - images/ic_loading_7.png
    - images/ic_loading_8.png
    - images/ic_loading_9.png
    - images/ic_loading_10.png
    - images/ic_loading_11.png
    - images/ic_loading_12.png
    - images/ic_loading_13.png
    - images/ic_loading_14.png
    - images/ic_loading_15.png
    - images/ic_loading_16.png
    - images/ic_loading_17.png
    - images/ic_loading_18.png
    - images/ic_loading_19.png
    - images/ic_loading_20.png
    - images/ic_loading_21.png
    - images/ic_loading_22.png
    - images/ic_loading_23.png
    - images/ic_loading_24.png
    - images/ic_loading_25.png
    - images/ic_loading_26.png
    - images/ic_loading_27.png
    - images/ic_loading_28.png
    - images/ic_loading_29.png
    - images/ic_load_empty_dark.png
    - images/ic_load_empty_normal.png
    - images/ic_load_error_dark.png
    - images/ic_load_error_normal.png
    - images/ic_load_failure_dark.png
    - images/ic_load_failure_normal.png
    - images/common_ptr_l_0.png
    - images/common_ptr_l_1.png
    - images/common_ptr_l_2.png
    - images/common_ptr_l_3.png
    - images/common_ptr_l_4.png
    - images/common_ptr_l_5.png
    - images/common_ptr_l_6.png
    - images/common_ptr_l_7.png
    - images/common_ptr_l_8.png
    - images/common_ptr_l_9.png
    - images/common_ptr_l_10.png
    - images/common_ptr_l_11.png
    - images/common_ptr_l_12.png
    - images/common_ptr_l_13.png
    - images/common_ptr_l_14.png
    - images/common_ptr_l_15.png
    - images/common_ptr_l_16.png
    - images/common_ptr_l_17.png
    - images/common_ptr_l_18.png
    - images/common_ptr_l_19.png
    - images/common_ptr_l_20.png
    - images/common_ptr_l_21.png
    - images/common_ptr_l_22.png
    - images/common_ptr_l_23.png
    - images/common_ptr_l_24.png
    - images/common_ptr_l_25.png
    - images/common_ptr_l_26.png
    - images/common_ptr_l_27.png
    - images/common_ptr_l_28.png
    - images/common_ptr_l_29.png
    - images/common_ptr_nomore.png
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
